export const USER_ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  NATIONAL_COMMAND: 'NATIONAL_COMMAND',
  PROVINCIAL_COMMANDER: 'PROVINCIAL_COMMANDER',
  STATION_COMMANDER: 'STATION_COMMANDER',
  FIELD_OFFICER: 'FIELD_OFFICER',
  ANALYST: 'ANALYST',
};

export const ALL_USER_ROLES = Object.values(USER_ROLES);

export const WRITE_ACCESS_ROLES = [
  USER_ROLES.SUPER_ADMIN,
  USER_ROLES.NATIONAL_COMMAND,
  USER_ROLES.PROVINCIAL_COMMANDER,
  USER_ROLES.STATION_COMMANDER,
];

export const USER_ADMIN_ROLES = [USER_ROLES.SUPER_ADMIN, USER_ROLES.NATIONAL_COMMAND];

