export const USER_ROLES = {
  HQ_ADMIN: 'HQ_ADMIN',
  PROVINCIAL_ADMIN: 'PROVINCIAL_ADMIN',
  DISTRICT_OFFICER: 'DISTRICT_OFFICER',
  STATION_OFFICER: 'STATION_OFFICER',
  DEVICE_CLIENT: 'DEVICE_CLIENT',
};

export const ALL_USER_ROLES = Object.values(USER_ROLES);
export const HUMAN_USER_ROLES = ALL_USER_ROLES.filter((role) => role !== USER_ROLES.DEVICE_CLIENT);

export const WRITE_ACCESS_ROLES = [
  USER_ROLES.HQ_ADMIN,
  USER_ROLES.PROVINCIAL_ADMIN,
  USER_ROLES.DISTRICT_OFFICER,
  USER_ROLES.STATION_OFFICER,
];

export const USER_ADMIN_ROLES = [USER_ROLES.HQ_ADMIN, USER_ROLES.PROVINCIAL_ADMIN];
